import { Router } from 'express';
import health from './health.js';
import auth from './auth.js';
import profile from './profile.js';
import courses from './courses.js';
import enrollments from './enrollments.js';
import credentials from './credentials.js';
import techDeclarations from './techDeclarations.js';
import tags from './tags.js';
import admin from './admin.js';
import deepSubmissions from './deepSubmissions.js';
import quippy from './quippy.js';
import operator from './operator.js';
import endorsements from './endorsements.js';
import webhooks from './webhooks.js';
import discovery from './discovery.js';
import introductions from './introductions.js';
import marketplace from './marketplace.js';
import leads from './leads.js';
import supplier from './supplier.js';

const router = Router();

router.use('/health', health);
router.use('/auth', auth);
router.use('/profile', profile);
router.use('/courses', courses);
router.use('/enrollments', enrollments);
router.use('/credentials', credentials);
router.use('/tech-declarations', techDeclarations);
router.use('/tags', tags);
router.use('/admin', admin);
router.use('/deep-submissions', deepSubmissions);
router.use('/quippy', quippy);
router.use('/operator', operator);
router.use('/endorsements', endorsements);
router.use('/webhooks', webhooks);
router.use('/discovery', discovery);
router.use('/introductions', introductions);
router.use('/marketplace', marketplace);
router.use('/leads', leads);
router.use('/supplier', supplier);

export default router;
